services:
  postgres:
    image: postgres:16
    container_name: tsukinote_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tsukinote
      POSTGRES_USER: tsukinote_user
      POSTGRES_PASSWORD: tsukinote_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: